/**
 * Nigerian states (36 + FCT) and Local Government Areas.
 * Source: Wikipedia — Local government areas of Nigeria.
 */

export const NIGERIAN_STATES: string[] = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Federal Capital Territory",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const LGAS_BY_STATE: Record<string, string[]> = {
  Abia: [
    "Umu Nneochi", "Umuahia South", "Umuahia North", "Ukwa West", "Ukwa East",
    "Ugwunagbo", "Osisioma Ngwa", "Ohafia", "Obi Ngwa", "Isuikwuato",
    "Isiala Ngwa South", "Isiala Ngwa North", "Ikwuano", "Bende", "Arochukwu",
    "Aba South", "Aba North",
  ],
  Adamawa: [
    "Yola South", "Yola North", "Toungo", "Song", "Shelleng", "Numan",
    "Mubi South", "Mubi North", "Michika", "Mayo Belwa", "Maiha", "Madagali",
    "Lamurde", "Jada", "Hong", "Gombi", "Girei", "Guyuk", "Ganye", "Fufure",
    "Demsa",
  ],
  "Akwa Ibom": [
    "Uyo", "Urue-Offong/Oruko", "Uruan", "Ukanafun", "Udung-Uko", "Oruk Anam",
    "Oron", "Onna", "Okobo", "Obot Akara", "Nsit-Ubium", "Nsit-Ibom", "Nsit-Atai",
    "Mkpat-Eni", "Mbo", "Itu", "Ini", "Ikot Ekpene", "Ikot Abasi", "Ikono",
    "Ika", "Ibiono-Ibom", "Ibesikpo Asutan", "Ibeno", "Etinan", "Etim Ekpo",
    "Essien Udim", "Esit Eket", "Eket", "Eastern Obolo", "Abak",
  ],
  Anambra: [
    "Oyi", "Orumba South", "Orumba North", "Onitsha South", "Onitsha North",
    "Ogbaru", "Nnewi South", "Nnewi North", "Njikoka", "Ihiala", "Idemili South",
    "Idemili North", "Ekwusigo", "Dunukofia", "Ayamelum", "Awka South", "Awka North",
    "Anaocha", "Anambra West", "Anambra East", "Aguata",
  ],
  Bauchi: [
    "Zaki", "Warji", "Toro", "Tafawa Balewa", "Shira", "Ningi", "Misau", "Kirfi",
    "Katagum", "Jama'are", "Itas/Gadau", "Giade", "Ganjuwa", "Gamawa", "Dass",
    "Darazo", "Damban", "Bogoro", "Bauchi", "Alkaleri",
  ],
  Bayelsa: [
    "Yenagoa", "Southern Ijaw", "Sagbama", "Ogbia", "Nembe", "Kolokuma/Opokuma",
    "Ekeremor", "Brass",
  ],
  Benue: [
    "Vandeikya", "Ushongo", "Ukum", "Tarka", "Oturkpo", "Okpokwu", "Oju",
    "Ohimini", "Ogbadibo", "Obi", "Makurdi", "Logo", "Kwande", "Konshisha",
    "Katsina-Ala", "Gwer West", "Gwer East", "Guma", "Gboko", "Buruku", "Apa",
    "Agatu", "Ado",
  ],
  Borno: [
    "Shani", "Nganzai", "Ngala", "Monguno", "Mobbar", "Marte", "Maiduguri",
    "Magumeri", "Mafa", "Kwaya Kusar", "Kukawa", "Konduga", "Kala/Balge", "Kaga",
    "Jere", "Hawul", "Gwoza", "Guzamala", "Gubio", "Dikwa", "Damboa", "Chibok",
    "Biu", "Bayo", "Bama", "Askira/Uba", "Abadam",
  ],
  "Cross River": [
    "Yala", "Yakurr", "Ogoja", "Odukpani", "Obudu", "Obubra", "Obanliku", "Ikom",
    "Etung", "Calabar South", "Calabar Municipal", "Boki", "Biase", "Bekwarra",
    "Bakassi", "Akpabuyo", "Akamkpa", "Abi",
  ],
  Delta: [
    "Warri South West", "Warri South", "Warri North", "Uvwie", "Ukwuani",
    "Ughelli South", "Ughelli North", "Udu", "Sapele", "Patani", "Oshimili South",
    "Oshimili North", "Okpe", "Ndokwa West", "Ndokwa East", "Isoko South",
    "Isoko North", "Ika South", "Ika North East", "Ethiope West", "Ethiope East",
    "Burutu", "Bomadi", "Aniocha South", "Aniocha North",
  ],
  Ebonyi: [
    "Onicha", "Ohaukwu", "Ohaozara", "Izzi", "Ivo", "Ishielu", "Ikwo", "Ezza South",
    "Ezza North", "Ebonyi", "Edda", "Afikpo", "Abakaliki",
  ],
  Edo: [
    "Uhunmwonde", "Owan West", "Owan East", "Ovia South-West", "Ovia North-East",
    "Oredo", "Orhionmwon", "Ikpoba Okha", "Igueben", "Etsako West", "Etsako East",
    "Etsako Central", "Esan West", "Esan South-East", "Esan North-East", "Esan Central",
    "Egor", "Akoko-Edo",
  ],
  Ekiti: [
    "Oye", "Moba", "Ise/Orun", "Irepodun/Ifelodun", "Ilejemeje", "Ikole", "Ikere",
    "Ijero", "Ido Osi", "Gbonyin", "Emure", "Ekiti West", "Ekiti South-West",
    "Ekiti East", "Efon", "Ado Ekiti",
  ],
  Enugu: [
    "Uzo-Uwani", "Udi", "Udenu", "Oji River", "Nsukka", "Nkanu West", "Nkanu East",
    "Isi Uzo", "Igbo Eze South", "Igbo Eze North", "Igbo Etiti", "Ezeagu",
    "Enugu South", "Enugu North", "Enugu East", "Awgu", "Aninri",
  ],
  "Federal Capital Territory": [
    "Gwagwalada", "Bwari", "Kuje", "Kwali", "Abuja Municipal Area Council", "Abaji",
  ],
  Gombe: [
    "Yamaltu/Deba", "Shongom", "Nafada", "Kwami", "Kaltungo", "Gombe", "Funakaye",
    "Dukku", "Billiri", "Balanga", "Akko",
  ],
  Imo: [
    "Onuimo", "Owerri West", "Owerri North", "Owerri Municipal", "Oru West", "Oru East",
    "Orsu", "Orlu", "Okigwe", "Ohaji/Egbema", "Oguta", "Obowo", "Nwangele", "Nkwerre",
    "Njaba", "Ngor Okpala", "Mbaitoli", "Isu", "Isiala Mbano", "Ikeduru",
    "Ihitte/Uboma", "Ideato South", "Ideato North", "Ezinihitte", "Ehime Mbano",
    "Ahiazu Mbaise", "Aboh Mbaise",
  ],
  Jigawa: [
    "Yankwashi", "Taura", "Sule Tankarkar", "Roni", "Ringim", "Miga", "Malam Madori",
    "Maigatari", "Kiyawa", "Kiri Kasama", "Kazaure", "Kaugama", "Kafin Hausa", "Jahun",
    "Hadejia", "Gwiwa", "Gwaram", "Guri", "Gumel", "Garki", "Gagarawa", "Dutse",
    "Buji", "Birnin Kudu", "Birniwa", "Babura", "Auyo",
  ],
  Kaduna: [
    "Zaria", "Zangon Kataf", "Soba", "Sanga", "Sabon Gari", "Makarfi", "Lere",
    "Kudan", "Kubau", "Kauru", "Kaura", "Kajuru", "Kagarko", "Kaduna South",
    "Kaduna North", "Kachia", "Jema'a", "Jaba", "Ikara", "Igabi", "Giwa", "Chikun",
    "Birnin Gwari",
  ],
  Kano: [
    "Wudil", "Warawa", "Ungogo", "Tudun Wada", "Tsanyawa", "Tofa", "Tarauni", "Takai",
    "Sumaila", "Shanono", "Rogo", "Rimin Gado", "Rano", "Nasarawa", "Minjibir",
    "Makoda", "Madobi", "Kura", "Kunchi", "Kumbotso", "Kiru", "Kibiya", "Karaye",
    "Kano Municipal", "Kabo", "Gwarzo", "Gwale", "Gezawa", "Gaya", "Garun Mallam",
    "Garko", "Gabasawa", "Fagge", "Doguwa", "Dawakin Tofa", "Dawakin Kudu", "Dambatta",
    "Dala", "Bunkure", "Bichi", "Bebeji", "Bagwai", "Albasu", "Ajingi",
  ],
  Katsina: [
    "Zango", "Sandamu", "Safana", "Sabuwa", "Rimi", "Musawa", "Matazu", "Mashi",
    "Mani", "Malumfashi", "Mai'Adua", "Kusada", "Kurfi", "Katsina", "Kankia", "Kankara",
    "Kaita", "Kafur", "Jibia", "Ingawa", "Funtua", "Faskari", "Dutsin Ma", "Dutsi",
    "Daura", "Dan Musa", "Danja", "Dandume", "Charanchi", "Bindawa", "Baure",
    "Batsari", "Batagarawa", "Bakori",
  ],
  Kebbi: [
    "Zuru", "Yauri", "Wasagu/Danko", "Suru", "Shanga", "Sakaba", "Ngaski", "Maiyama",
    "Koko/Besse", "Kalgo", "Jega", "Gwandu", "Fakai", "Dandi", "Bunza", "Birnin Kebbi",
    "Bagudo", "Augie", "Argungu", "Arewa", "Aleiro",
  ],
  Kogi: [
    "Omala", "Olamaboro", "Lokoja", "Okehi", "Okene", "Ofu", "Yagba East", "Yagba West",
    "Ijumu", "Mopa-Muro", "Kabba/Bunu", "Igalamela-Odolu", "Idah", "Ibaji", "Dekina",
    "Bassa", "Ankpa", "Ajaokuta", "Adavi",
  ],
  Kwara: [
    "Ilorin South", "Edu", "Asa", "Baruten", "Pategi", "Oyun", "Oke Ero", "Offa",
    "Moro", "Kaiama", "Isin", "Irepodun", "Ilorin West", "Ilorin East", "Ifelodun",
    "Ekiti",
  ],
  Lagos: [
    "Surulere", "Shomolu", "Oshodi-Isolo", "Ojo", "Mushin", "Lagos Mainland",
    "Lagos Island", "Kosofe", "Ikorodu", "Ikeja", "Ifako-Ijaiye", "Ibeju-Lekki",
    "Eti Osa", "Epe", "Badagry", "Apapa", "Amuwo-Odofin", "Alimosho",
    "Ajeromi-Ifelodun", "Agege",
  ],
  Nasarawa: [
    "Toto", "Wamba", "Nasarawa Eggon", "Nasarawa", "Keffi", "Kokona", "Obi", "Keana",
    "Lafia", "Karu", "Doma", "Awe", "Akwanga",
  ],
  Niger: [
    "Wushishi", "Tafa", "Suleja", "Shiroro", "Rijau", "Rafi", "Paikoro", "Munya",
    "Mokwa", "Mashegu", "Mariga", "Magama", "Lavun", "Lapai", "Kontagora", "Katcha",
    "Gurara", "Gbako", "Edati", "Chanchaga", "Bosso", "Borgu", "Bida", "Agwara",
    "Agaie",
  ],
  Ogun: [
    "Isara", "Yewa South", "Yewa North", "Shagamu", "Remo North", "Ogun Waterside",
    "Odogbolu", "Odeda", "Obafemi Owode", "Ipokia", "Imeko Afon", "Ikenne",
    "Ijebu East", "Ijebu Ode", "Ijebu North East", "Ijebu North", "Ifo", "Ewekoro",
    "Ado-Odo/Ota", "Abeokuta South", "Abeokuta North",
  ],
  Ondo: [
    "Owo", "Ose", "Ondo East", "Ondo West", "Okitipupa", "Odigbo", "Irele",
    "Ile-Oluji/Okeigbo", "Ilaje", "Idanre", "Ifedore", "Ese Odo", "Akure South",
    "Akure North", "Akoko South-West", "Akoko South-East", "Akoko North-West",
    "Akoko North-East",
  ],
  Osun: [
    "Osogbo", "Iwo", "Irepodun", "Orolu", "Ori-Ade", "Ila", "Odo-Otin", "Ilesa East",
    "Ilesa West", "Olorunda", "Ola-Oluwa", "Irewole", "Obokun", "Isokan", "Ifelodun",
    "Ifedayo", "Ife South", "Ife North", "Ife East", "Ife Central", "Ejigbo",
    "Egbedore", "Ede South", "Ede North", "Boripe", "Boluwaduro", "Atakunmosa West",
    "Atakunmosa East", "Aiyedire", "Aiyedaade",
  ],
  Oyo: [
    "Oyo West", "Oyo East", "Atiba", "Lagelu", "Egbeda", "Saki East", "Saki West",
    "Atisbo", "Orire", "Orelope", "Ona Ara", "Oluyole", "Olorunsogo", "Ogo Oluwa",
    "Ogbomosho South", "Ogbomosho North", "Iwajowa", "Irepo", "Ido", "Ibarapa North",
    "Ibarapa East", "Ibarapa Central", "Ibadan South-West", "Ibadan South-East",
    "Ibadan North-West", "Ibadan North-East", "Ibadan North", "Afijio",
  ],
  Plateau: [
    "Wase", "Shendam", "Riyom", "Qua'an-Pan", "Pankshin", "Mikang", "Mangu",
    "Langtang South", "Langtang North", "Kanke", "Kanam", "Jos South", "Jos North",
    "Jos East", "Bokkos", "Bassa", "Barkin Ladi",
  ],
  Rivers: [
    "Tai", "Port Harcourt", "Oyigbo", "Opobo-Nkoro", "Omuma", "Okirika", "Ogu-Bolo",
    "Ogba-Egbema-Ndoni", "Obio-Akpor", "Khana", "Ikwerre", "Gokana", "Etche",
    "Emohua", "Eleme", "Degema", "Bonny", "Asari Toru", "Andoni", "Akuku Toru",
    "Ahoada West", "Ahoada East", "Abua-Odual",
  ],
  Sokoto: [
    "Kware", "Tambuwal", "Tureta", "Gudu", "Illela", "Goronyo", "Wurno", "Silame",
    "Rabah", "Isah", "Sabon Birni", "Bodinga", "Tangaza", "Wamakko", "Gwadabawa",
    "Sokoto North", "Sokoto South", "Gada", "Dange Shuni", "Binji",
  ],
  Taraba: [
    "Zing", "Yorro", "Wukari", "Ussa", "Takum", "Sardauna", "Lau", "Kurmi",
    "Karim Lamido", "Jalingo", "Ibi", "Gassol", "Gashaka", "Donga", "Bali", "Ardo Kola",
  ],
  Yobe: [
    "Yusufari", "Yunusari", "Tarmuwa", "Potiskum", "Nguru", "Nangere", "Machina",
    "Karasuwa", "Jakusko", "Gulani", "Gujba", "Geidam", "Fune", "Fika", "Damaturu",
    "Bursari", "Bade",
  ],
  Zamfara: [
    "Zurmi", "Talata-Mafara", "Shinkafi", "Maru", "Maradun", "Kaura-Namoda", "Gusau",
    "Gummi", "Tsafe", "Bungudu", "Bukkuyum", "Birnin Magaji/Kiyaw", "Bakura", "Anka",
  ],
};
